### ISSUE TITLE
How to difference between snippets with same name but different language

### ISSUE THREAD

**Issue by kun65** [ZeroX-DG/vscode-snippetstore#2]
Hello,
I defined snippets with the same name in various languages, for example 'foreach' in PowerShell, Perl and C#. If I call 'Import snippets from Snippet Store' I get all snippets not only these for the actual programming language.
If the snippets can not be filtered it would be nice if the programming language would be shown for of each snippet (as symbol or text).

**Comment by ZeroX-DG** [comment]
I'm planning to add programming language icon next to the name of each snippet. I still not figure it out how to do that. If you happen to know how don't hesitate to submit a PR.

**Comment by ZeroX-DG** [comment]
I have added a language name below the snippet name in the latest version that I released.
