### ISSUE TITLE
extension not working at all

### ISSUE THREAD

**Issue by NavjotSingh007** [ZeroX-DG/vscode-snippetstore#4]
After selecting some block of code > right click/Ctrl+Shift+p > transfer snippets to snippet store/import snippet from snippet store > nothing happens.

Please look into the issue as I really liked the idea of this extension

Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Comment by ZeroX-DG** [comment]
Are you sure that you have SnippetStore running when you transfer your code?

**Comment by NavjotSingh007** [comment]
I did installed your extension and its status is also marked as installed, I can also see snippet store commands in ctrl+shift+p

If there's any other way, We can make sure snippet stode is running, Please let me know

**Comment by ZeroX-DG** [comment]
You must first run SnippetStore and then run vscode with the vscode-snippetstore extension enabled. Then highlight your code and click transfer snippet.

**Comment by NavjotSingh007** [comment]
snippet store itself is not opening.

**Comment by ZizhouJia** [comment]
How to open the store
